### ISSUE TITLE
Aliases Issue

### ISSUE THREAD

**Issue by ghost** [Mastagoon/untrusted-discord#4]
Aliases for investigative mole do not work properly. A couple work (if you need evidence, etc. Add or ping Arch1010#4338 in untrusted discord.)

**Comment by Mastagoon** [comment]
Hello, thank you for reporting the issue. I would like to see learn more details about this, I will message you on discord.

**Comment by Mastagoon** [comment]
Closing this as the problem seems to be from the seeding of the live bot. Testing showed the aliases working fine with clean files.
