### ISSUE TITLE
PlayerCount API

### ISSUE THREAD

**Issue by Arch881010** [Mastagoon/untrusted-discord#6]
Trying to run the bot locally and use the playercount command returns with `This feature is currently disabled.`
Fetching the api to test the issuse ([https://eu01.playuntrusted.com/publicAPI/publicAPI.php?request=getPlayerCount](url)) using node fetch returns with:  `[ { error: 'Invalid API key.' } ]`
Downloading the response.json file pulls up: `[ { error: 'Invalid API key.' } ]` as well.
Any ideas?

**Comment by Mastagoon** [comment]
Hello Arch.
The API is provided by Knu , and he already said he's going to implement an API key feature to prevent spam. Please contact Knu on discord Knu#0835

**Comment by Arch881010** [comment]
Alright, thank you for this information!
