### ISSUE TITLE
Playercount has the wrong description.

### ISSUE THREAD

**Issue by Arch881010** [Mastagoon/untrusted-discord#7]

**Comment by Arch881010** [comment]
![08DFAEF8-73E0-4116-9317-0D11EEE7C2E0](https://user-images.githubusercontent.com/111789310/213888651-17e6aa8c-ed96-43a4-8ebc-76a86e2afe89.jpeg)
![4249020C-0411-4EB4-A1ED-B5B9CF8A8D95](https://user-images.githubusercontent.com/111789310/213888652-eecb1c4e-6fd2-4868-ac0d-4dbbfd9e3526.jpeg)
![E419447B-6A01-47C8-A337-B49FEBE57633](https://user-images.githubusercontent.com/111789310/213888653-27750b12-738f-4607-8374-10902706354e.jpeg)

**Comment by Mastagoon** [comment]
Thank you for reporting this. I've fixed it on the codebase.
